// Content library for industry-specific stealth gaming content
export interface IndustryContent {
  industry: string;
  struggle: string;
  technicalDeepDive: string;
  stealthProtocol: string;
  safetyGuidelines: string;
}

export const contentLibrary: IndustryContent[] = [
  {
    industry: 'Finance',
    struggle: `Finance professionals face unprecedented RTO pressure as late-stage capitalism demands constant presence on the trading floor. The return to physical desks has amplified anxiety levels, with traders reporting 30% higher cortisol levels during market hours. The pressure to maintain alpha while navigating open-floor surveillance creates a toxic cocktail of stress and paranoia. Compliance departments now require mandatory screen recording during trading sessions, turning the office into a panopticon of performance anxiety. The constant fear of being flagged for non-work activity has led to a surge in burnout rates, with 40% of analysts reporting symptoms of occupational burnout.`,
    technicalDeepDive: `Bloomberg Terminal monitoring systems use proprietary keystroke logging technology to track trader activity in real-time. The Bloomberg EMSX platform integrates with compliance software that analyzes keystroke patterns, mouse movements, and application usage to create a "productivity score" for each trader. Goldman Sachs' internally developed "Productivity Tracker" uses machine learning algorithms to identify deviations from normal trading patterns, flagging any activity that falls outside predefined thresholds. These systems also monitor network traffic, blocking access to non-approved domains and logging all external communications for compliance review.`,
    stealthProtocol: `StealthPlay bypasses finance sector firewalls through a multi-layered approach: 1) Pixel offset technology that mimics Bloomberg Terminal UI elements, creating a convincing overlay that appears identical to legitimate trading software. 2) Packet obfuscation that encrypts gaming traffic to appear as Bloomberg API calls, using the same port numbers and encryption protocols as legitimate financial data. 3) Keystroke pattern mimicry that analyzes and reproduces the specific typing cadence of finance professionals, avoiding detection by behavioral analytics systems. 4) Real-time screen analysis that automatically switches to legitimate Bloomberg Terminal views when motion is detected in the peripheral vision area.`,
    safetyGuidelines: `Finance professionals should follow these职场生存建议: 1) Maintain a consistent "work face" even when gaming, with occasional glances at the Bloomberg Terminal and deliberate keyboard activity. 2) Create a "cover story" project that requires periodic research, providing a legitimate reason for screen activity. 3) Use the bathroom as a strategic reset point, allowing time for mental breaks without appearing suspicious. 4) Schedule regular coffee breaks to mimic normal workplace behavior patterns. 5) Keep a physical notepad with financial jargon nearby, ready to scribble notes if approached by management. 6) Set up keyboard macros that trigger legitimate Bloomberg Terminal functions with a single keystroke for quick cover.`,
  },
  {
    industry: 'Tech',
    struggle: `Tech workers face unique RTO challenges as late-stage capitalism demands constant innovation while monitoring productivity metrics. The return to office has created a paradox: companies tout "collaboration" while implementing invasive monitoring tools that track every keystroke and mouse movement. GitLab activity dashboards now publicly display developer throughput, creating a toxic culture of performative coding. The pressure to maintain high commit rates has led to a surge in "fake work" — developers creating meaningless commits to appear productive. Burnout rates in tech have increased by 25% post-RTO, with many developers reporting feeling like "digital sharecroppers" in open office environments.`,
    technicalDeepDive: `GitLab's activity monitoring system uses webhook integrations to track every commit, merge request, and code review in real-time. The platform's analytics dashboard provides managers with granular insights into developer productivity, including lines of code written, commit frequency, and time spent in the IDE. Many tech companies augment this with screen recording software like Teramind, which captures every keystroke and mouse movement, analyzing patterns to identify "non-productive" time. Network monitoring tools like Zscaler track all outbound traffic, blocking access to gaming domains and logging attempts to circumvent restrictions.`,
    stealthProtocol: `StealthPlay bypasses tech sector monitoring through: 1) IDE skin technology that overlays gaming interfaces with convincing VS Code or IntelliJ UI elements, complete with syntax highlighting and code snippets. 2) Commit pattern mimicry that generates periodic fake commits with realistic code changes, maintaining GitLab activity metrics. 3) Network traffic tunneling that encrypts gaming data and routes it through legitimate development APIs like GitHub or npm. 4) Mouse movement simulation that replicates the erratic but purposeful patterns of developers debugging code, avoiding detection by behavioral analytics systems. 5) Background compilation noise that mimics the sound of a busy developer environment, covering any gaming audio.`,
    safetyGuidelines: `Tech workers should follow these职场生存建议: 1) Maintain a consistent "debugging face" — furrowed brow, occasional head scratching, and muttered technical jargon. 2) Set up automated scripts that generate legitimate-looking commits at regular intervals. 3) Use dual monitors strategically, with one displaying legitimate code and the other running the game with IDE skin overlay. 4) Schedule regular stand-up breaks to mimic normal developer behavior patterns. 5) Keep a whiteboard with technical diagrams nearby, ready to explain your "current project" if approached. 6) Use keyboard shortcuts that trigger both gaming actions and legitimate IDE functions simultaneously.`,
  },
  {
    industry: 'Legal',
    struggle: `Legal professionals face intense RTO pressure as billable hours targets remain sky-high while firms implement invasive monitoring systems. The return to office has created a surveillance state in law firms, with partners demanding constant visibility into associate activity. Billable hours tracking software now monitors every second of the workday, creating a culture of "presenteeism" where attorneys feel compelled to remain at their desks even when not actively billing. The pressure to maintain 1800+ billable hours annually has led to a 35% increase in attorney burnout rates post-RTO. Many associates report feeling like "billable machines" rather than legal professionals, with little time for actual legal thinking.`,
    technicalDeepDive: `Clio and TimeSolv billable hours tracking systems integrate with desktop monitoring software that captures every application used and every website visited, categorizing time as "billable" or "non-billable." Firms like Kirkland & Ellis use proprietary "Productivity Trackers" that monitor keyboard activity, mouse movements, and even eye tracking to ensure associates remain focused on billable work. Network monitoring tools block access to non-legal websites and log all external communications, with compliance departments reviewing these logs weekly. Some firms even implement facial recognition systems to track when associates are at their desks.`,
    stealthProtocol: `StealthPlay bypasses legal sector monitoring through: 1) Document review skin technology that overlays gaming interfaces with convincing legal document templates, complete with redline markup and citation formatting. 2) Time entry mimicry that automatically generates plausible billable time entries for "document review" or "legal research" at regular intervals. 3) Network traffic obfuscation that encrypts gaming data to appear as Westlaw or LexisNexis research queries. 4) Keyboard pattern mimicry that reproduces the specific typing cadence of legal professionals reviewing documents. 5) Background document scanning sounds that mimic the audio of a busy legal office, covering any gaming audio.`,
    safetyGuidelines: `Legal professionals should follow these职场生存建议: 1) Maintain a consistent "document review face" — furrowed brow, occasional note-taking, and muttered legal analysis. 2) Keep physical legal documents nearby, ready to flip through if approached by partners. 3) Schedule regular coffee breaks to mimic normal attorney behavior patterns. 4) Use dual monitors strategically, with one displaying legitimate legal documents and the other running the game with document review skin overlay. 5) Create a "research project" cover story that requires periodic online research, providing a legitimate reason for screen activity. 6) Use keyboard shortcuts that trigger both gaming actions and legitimate document review functions simultaneously.`,
  },
  {
    industry: 'Healthcare',
    struggle: `Healthcare professionals face unique RTO challenges as hospitals and clinics demand constant presence while implementing patient data security monitoring. The return to office has created additional stress for healthcare workers already burned out by the pandemic. Electronic Health Record (EHR) systems now track every keystroke and mouse movement, with compliance departments reviewing these logs to ensure HIPAA compliance. The pressure to maintain high patient throughput while navigating surveillance systems has led to a 40% increase in healthcare worker burnout rates post-RTO. Many healthcare professionals report feeling like "data entry clerks" rather than caregivers, with little time for actual patient interaction.`,
    technicalDeepDive: `Epic and Cerner EHR systems integrate with surveillance software that monitors all user activity to ensure HIPAA compliance. These systems track every patient record accessed, every medication ordered, and every note entered, flagging any activity that falls outside normal patterns. Hospitals also implement network monitoring tools that block access to non-medical websites and log all external communications. Some healthcare systems even use keystroke logging software to ensure that healthcare professionals are properly documenting patient care in real-time.`,
    stealthProtocol: `StealthPlay bypasses healthcare sector monitoring through: 1) EHR skin technology that overlays gaming interfaces with convincing Epic or Cerner UI elements, complete with patient data fields and medication order forms. 2) Documentation pattern mimicry that automatically generates plausible patient notes at regular intervals. 3) Network traffic obfuscation that encrypts gaming data to appear as medical research queries or EHR system updates. 4) Keyboard pattern mimicry that reproduces the specific typing cadence of healthcare professionals documenting patient care. 5) Background medical equipment sounds that mimic the audio of a busy healthcare environment, covering any gaming audio.`,
    safetyGuidelines: `Healthcare professionals should follow these职场生存建议: 1) Maintain a consistent "patient documentation face" — focused expression, occasional head nodding, and muttered medical terminology. 2) Keep physical patient charts nearby, ready to review if approached by supervisors. 3) Schedule regular breaks to mimic normal healthcare worker behavior patterns. 4) Use dual monitors strategically, with one displaying legitimate EHR records and the other running the game with EHR skin overlay. 5) Create a "professional development" cover story that requires periodic online research, providing a legitimate reason for screen activity. 6) Use keyboard shortcuts that trigger both gaming actions and legitimate EHR functions simultaneously.`,
  },
  {
    industry: 'Admin',
    struggle: `Administrative professionals face intense RTO pressure as companies demand constant presence while implementing productivity monitoring systems. The return to office has created a surveillance state for admin workers, with managers demanding constant visibility into their activities. Time tracking software now monitors every task and every minute of the workday, creating a culture of micro-management. The pressure to maintain high productivity metrics has led to a 30% increase in admin worker burnout rates post-RTO. Many admin professionals report feeling like "office drones" rather than valued team members, with little autonomy or control over their workday.`,
    technicalDeepDive: `Microsoft 365 productivity tracking tools monitor every document accessed, every email sent, and every meeting attended, providing managers with granular insights into admin worker productivity. Many companies augment this with screen recording software like Hubstaff, which captures every keystroke and mouse movement, analyzing patterns to identify "non-productive" time. Network monitoring tools block access to non-work websites and log all external communications, with HR departments reviewing these logs monthly. Some companies even implement desk sensors to track when admin workers are at their desks.`,
    stealthProtocol: `StealthPlay bypasses admin sector monitoring through: 1) Microsoft 365 skin technology that overlays gaming interfaces with convincing Outlook or Excel UI elements, complete with email threads and spreadsheet data. 2) Task completion mimicry that automatically generates plausible task updates in project management tools at regular intervals. 3) Network traffic obfuscation that encrypts gaming data to appear as Microsoft 365 API calls or SharePoint document updates. 4) Keyboard pattern mimicry that reproduces the specific typing cadence of administrative professionals processing emails and documents. 5) Background office sounds that mimic the audio of a busy administrative environment, covering any gaming audio.`,
    safetyGuidelines: `Administrative professionals should follow these职场生存建议: 1) Maintain a consistent "task processing face" — focused expression, occasional note-taking, and muttered task lists. 2) Keep physical documents nearby, ready to process if approached by managers. 3) Schedule regular coffee breaks to mimic normal admin worker behavior patterns. 4) Use dual monitors strategically, with one displaying legitimate Microsoft 365 applications and the other running the game with Microsoft 365 skin overlay. 5) Create a "project coordination" cover story that requires periodic online research, providing a legitimate reason for screen activity. 6) Use keyboard shortcuts that trigger both gaming actions and legitimate Microsoft 365 functions simultaneously.`,
  },
];
