import { create } from 'zustand';

interface GhostedEmail {
  name: string;
  email: string;
  lastContactDate: string;
  subjectPreview: string;
}

interface AppState {
  // State
  ghostedEmails: GhostedEmail[];
  loading: boolean;
  error: string | null;
  drawerOpen: boolean;
  selectedEmail: GhostedEmail | null;
  followUpMessage: string;
  showToast: boolean;
  paymentDialogOpen: boolean;
  isPaidUser: boolean;

  // Actions
  setGhostedEmails: (emails: GhostedEmail[]) => void;
  setLoading: (loading: boolean) => void;
  setError: (error: string | null) => void;
  setDrawerOpen: (open: boolean) => void;
  setSelectedEmail: (email: GhostedEmail | null) => void;
  setFollowUpMessage: (message: string) => void;
  setShowToast: (show: boolean) => void;
  setPaymentDialogOpen: (open: boolean) => void;
  setIsPaidUser: (isPaid: boolean) => void;
  fetchGhostedEmails: () => Promise<void>;
  fetchUserSubscription: () => Promise<void>;
  sendPing: (email: GhostedEmail, message: string) => Promise<void>;
}

export const useAppStore = create<AppState>((set, get) => ({
  // Initial state
  ghostedEmails: [],
  loading: false,
  error: null,
  drawerOpen: false,
  selectedEmail: null,
  followUpMessage: '',
  showToast: false,
  paymentDialogOpen: false,
  isPaidUser: false,

  // Actions
  setGhostedEmails: (emails) => set({ ghostedEmails: emails }),
  setLoading: (loading) => set({ loading }),
  setError: (error) => set({ error }),
  setDrawerOpen: (open) => set({ drawerOpen: open }),
  setSelectedEmail: (email) => set({ selectedEmail: email }),
  setFollowUpMessage: (message) => set({ followUpMessage: message }),
  setShowToast: (show) => set({ showToast: show }),
  setPaymentDialogOpen: (open) => set({ paymentDialogOpen: open }),
  setIsPaidUser: (isPaid) => set({ isPaidUser: isPaid }),

  fetchGhostedEmails: async () => {
    set({ loading: true, error: null });
    try {
      const response = await fetch('/api/ghosted', {
        headers: {
          'x-csrf-token': 'placeholder-token', // In a real app, this would be generated by the server
        },
      });
      if (response.ok) {
        const data = await response.json();
        set({ ghostedEmails: data });
      } else {
        const errorData = await response.json();
        set({ error: errorData.error || 'Failed to fetch ghosted emails' });
      }
    } catch (error) {
      console.error('Error fetching ghosted emails:', error);
      set({ error: 'Failed to connect to server. Please try again later.' });
    } finally {
      set({ loading: false });
    }
  },

  fetchUserSubscription: async () => {
    try {
      // In a real app, this would call an API to get the user's subscription status
      // For demo purposes, we'll simulate a check
      const session = await fetch('/api/auth/session');
      if (session.ok) {
        const sessionData = await session.json();
        if (sessionData.user?.email) {
          // Simulate subscription check
          // In production, this would be a real API call to your subscription service
          const isPaid = Math.random() > 0.7; // 30% chance to be a paid user for demo
          set({ isPaidUser: isPaid });
        }
      }
    } catch (error) {
      console.error('Error fetching user subscription:', error);
      set({ isPaidUser: false });
    }
  },

  sendPing: async (email, message) => {
    const { isPaidUser, fetchGhostedEmails } = get();
    
    if (!isPaidUser) {
      set({ drawerOpen: false, paymentDialogOpen: true });
      return;
    }
    
    try {
      const response = await fetch('/api/send-ping', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-csrf-token': 'placeholder-token', // In a real app, this would be generated by the server
        },
        body: JSON.stringify({
          to: email.email,
          subject: `Re: ${email.subjectPreview.replace('...', '')}`,
          message,
        }),
      });

      if (response.ok) {
        // Close drawer after sending
        set({ drawerOpen: false, selectedEmail: null, followUpMessage: '' });
        
        // Show success toast
        set({ showToast: true });
        setTimeout(() => set({ showToast: false }), 3000);
        
        // Refresh the ghosted emails list
        await fetchGhostedEmails();
      } else {
        const errorData = await response.json();
        console.error('Error sending ping:', errorData.error);
        set({ error: errorData.error || 'Failed to send ping' });
        setTimeout(() => set({ error: null }), 5000);
      }
    } catch (error) {
      console.error('Error sending ping:', error);
      set({ error: 'Failed to connect to server. Please try again later.' });
      setTimeout(() => set({ error: null }), 5000);
    }
  },
}));
