
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Context` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Context
 * 
 */
export type ContextModel = runtime.Types.Result.DefaultSelection<Prisma.$ContextPayload>

export type AggregateContext = {
  _count: ContextCountAggregateOutputType | null
  _min: ContextMinAggregateOutputType | null
  _max: ContextMaxAggregateOutputType | null
}

export type ContextMinAggregateOutputType = {
  id: string | null
  title: string | null
  content: string | null
  hook: string | null
  createdAt: Date | null
}

export type ContextMaxAggregateOutputType = {
  id: string | null
  title: string | null
  content: string | null
  hook: string | null
  createdAt: Date | null
}

export type ContextCountAggregateOutputType = {
  id: number
  title: number
  content: number
  hook: number
  createdAt: number
  _all: number
}


export type ContextMinAggregateInputType = {
  id?: true
  title?: true
  content?: true
  hook?: true
  createdAt?: true
}

export type ContextMaxAggregateInputType = {
  id?: true
  title?: true
  content?: true
  hook?: true
  createdAt?: true
}

export type ContextCountAggregateInputType = {
  id?: true
  title?: true
  content?: true
  hook?: true
  createdAt?: true
  _all?: true
}

export type ContextAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Context to aggregate.
   */
  where?: Prisma.ContextWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Contexts to fetch.
   */
  orderBy?: Prisma.ContextOrderByWithRelationInput | Prisma.ContextOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ContextWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Contexts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Contexts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Contexts
  **/
  _count?: true | ContextCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ContextMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ContextMaxAggregateInputType
}

export type GetContextAggregateType<T extends ContextAggregateArgs> = {
      [P in keyof T & keyof AggregateContext]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateContext[P]>
    : Prisma.GetScalarType<T[P], AggregateContext[P]>
}




export type ContextGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ContextWhereInput
  orderBy?: Prisma.ContextOrderByWithAggregationInput | Prisma.ContextOrderByWithAggregationInput[]
  by: Prisma.ContextScalarFieldEnum[] | Prisma.ContextScalarFieldEnum
  having?: Prisma.ContextScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ContextCountAggregateInputType | true
  _min?: ContextMinAggregateInputType
  _max?: ContextMaxAggregateInputType
}

export type ContextGroupByOutputType = {
  id: string
  title: string
  content: string
  hook: string
  createdAt: Date
  _count: ContextCountAggregateOutputType | null
  _min: ContextMinAggregateOutputType | null
  _max: ContextMaxAggregateOutputType | null
}

export type GetContextGroupByPayload<T extends ContextGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ContextGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ContextGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ContextGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ContextGroupByOutputType[P]>
      }
    >
  >



export type ContextWhereInput = {
  AND?: Prisma.ContextWhereInput | Prisma.ContextWhereInput[]
  OR?: Prisma.ContextWhereInput[]
  NOT?: Prisma.ContextWhereInput | Prisma.ContextWhereInput[]
  id?: Prisma.StringFilter<"Context"> | string
  title?: Prisma.StringFilter<"Context"> | string
  content?: Prisma.StringFilter<"Context"> | string
  hook?: Prisma.StringFilter<"Context"> | string
  createdAt?: Prisma.DateTimeFilter<"Context"> | Date | string
}

export type ContextOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  hook?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ContextWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  hook?: string
  AND?: Prisma.ContextWhereInput | Prisma.ContextWhereInput[]
  OR?: Prisma.ContextWhereInput[]
  NOT?: Prisma.ContextWhereInput | Prisma.ContextWhereInput[]
  title?: Prisma.StringFilter<"Context"> | string
  content?: Prisma.StringFilter<"Context"> | string
  createdAt?: Prisma.DateTimeFilter<"Context"> | Date | string
}, "id" | "hook">

export type ContextOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  hook?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ContextCountOrderByAggregateInput
  _max?: Prisma.ContextMaxOrderByAggregateInput
  _min?: Prisma.ContextMinOrderByAggregateInput
}

export type ContextScalarWhereWithAggregatesInput = {
  AND?: Prisma.ContextScalarWhereWithAggregatesInput | Prisma.ContextScalarWhereWithAggregatesInput[]
  OR?: Prisma.ContextScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ContextScalarWhereWithAggregatesInput | Prisma.ContextScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Context"> | string
  title?: Prisma.StringWithAggregatesFilter<"Context"> | string
  content?: Prisma.StringWithAggregatesFilter<"Context"> | string
  hook?: Prisma.StringWithAggregatesFilter<"Context"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Context"> | Date | string
}

export type ContextCreateInput = {
  id?: string
  title: string
  content: string
  hook: string
  createdAt?: Date | string
}

export type ContextUncheckedCreateInput = {
  id?: string
  title: string
  content: string
  hook: string
  createdAt?: Date | string
}

export type ContextUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  hook?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContextUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  hook?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContextCreateManyInput = {
  id?: string
  title: string
  content: string
  hook: string
  createdAt?: Date | string
}

export type ContextUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  hook?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContextUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  hook?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContextCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  hook?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ContextMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  hook?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ContextMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  hook?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type ContextSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  hook?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["context"]>

export type ContextSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  hook?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["context"]>

export type ContextSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  hook?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["context"]>

export type ContextSelectScalar = {
  id?: boolean
  title?: boolean
  content?: boolean
  hook?: boolean
  createdAt?: boolean
}

export type ContextOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "content" | "hook" | "createdAt", ExtArgs["result"]["context"]>

export type $ContextPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Context"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    content: string
    hook: string
    createdAt: Date
  }, ExtArgs["result"]["context"]>
  composites: {}
}

export type ContextGetPayload<S extends boolean | null | undefined | ContextDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ContextPayload, S>

export type ContextCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ContextFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ContextCountAggregateInputType | true
  }

export interface ContextDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Context'], meta: { name: 'Context' } }
  /**
   * Find zero or one Context that matches the filter.
   * @param {ContextFindUniqueArgs} args - Arguments to find a Context
   * @example
   * // Get one Context
   * const context = await prisma.context.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ContextFindUniqueArgs>(args: Prisma.SelectSubset<T, ContextFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ContextClient<runtime.Types.Result.GetResult<Prisma.$ContextPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Context that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ContextFindUniqueOrThrowArgs} args - Arguments to find a Context
   * @example
   * // Get one Context
   * const context = await prisma.context.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ContextFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ContextFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContextClient<runtime.Types.Result.GetResult<Prisma.$ContextPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Context that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContextFindFirstArgs} args - Arguments to find a Context
   * @example
   * // Get one Context
   * const context = await prisma.context.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ContextFindFirstArgs>(args?: Prisma.SelectSubset<T, ContextFindFirstArgs<ExtArgs>>): Prisma.Prisma__ContextClient<runtime.Types.Result.GetResult<Prisma.$ContextPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Context that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContextFindFirstOrThrowArgs} args - Arguments to find a Context
   * @example
   * // Get one Context
   * const context = await prisma.context.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ContextFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ContextFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContextClient<runtime.Types.Result.GetResult<Prisma.$ContextPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Contexts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContextFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Contexts
   * const contexts = await prisma.context.findMany()
   * 
   * // Get first 10 Contexts
   * const contexts = await prisma.context.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const contextWithIdOnly = await prisma.context.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ContextFindManyArgs>(args?: Prisma.SelectSubset<T, ContextFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContextPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Context.
   * @param {ContextCreateArgs} args - Arguments to create a Context.
   * @example
   * // Create one Context
   * const Context = await prisma.context.create({
   *   data: {
   *     // ... data to create a Context
   *   }
   * })
   * 
   */
  create<T extends ContextCreateArgs>(args: Prisma.SelectSubset<T, ContextCreateArgs<ExtArgs>>): Prisma.Prisma__ContextClient<runtime.Types.Result.GetResult<Prisma.$ContextPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Contexts.
   * @param {ContextCreateManyArgs} args - Arguments to create many Contexts.
   * @example
   * // Create many Contexts
   * const context = await prisma.context.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ContextCreateManyArgs>(args?: Prisma.SelectSubset<T, ContextCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Contexts and returns the data saved in the database.
   * @param {ContextCreateManyAndReturnArgs} args - Arguments to create many Contexts.
   * @example
   * // Create many Contexts
   * const context = await prisma.context.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Contexts and only return the `id`
   * const contextWithIdOnly = await prisma.context.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ContextCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ContextCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContextPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Context.
   * @param {ContextDeleteArgs} args - Arguments to delete one Context.
   * @example
   * // Delete one Context
   * const Context = await prisma.context.delete({
   *   where: {
   *     // ... filter to delete one Context
   *   }
   * })
   * 
   */
  delete<T extends ContextDeleteArgs>(args: Prisma.SelectSubset<T, ContextDeleteArgs<ExtArgs>>): Prisma.Prisma__ContextClient<runtime.Types.Result.GetResult<Prisma.$ContextPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Context.
   * @param {ContextUpdateArgs} args - Arguments to update one Context.
   * @example
   * // Update one Context
   * const context = await prisma.context.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ContextUpdateArgs>(args: Prisma.SelectSubset<T, ContextUpdateArgs<ExtArgs>>): Prisma.Prisma__ContextClient<runtime.Types.Result.GetResult<Prisma.$ContextPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Contexts.
   * @param {ContextDeleteManyArgs} args - Arguments to filter Contexts to delete.
   * @example
   * // Delete a few Contexts
   * const { count } = await prisma.context.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ContextDeleteManyArgs>(args?: Prisma.SelectSubset<T, ContextDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Contexts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContextUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Contexts
   * const context = await prisma.context.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ContextUpdateManyArgs>(args: Prisma.SelectSubset<T, ContextUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Contexts and returns the data updated in the database.
   * @param {ContextUpdateManyAndReturnArgs} args - Arguments to update many Contexts.
   * @example
   * // Update many Contexts
   * const context = await prisma.context.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Contexts and only return the `id`
   * const contextWithIdOnly = await prisma.context.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ContextUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ContextUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContextPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Context.
   * @param {ContextUpsertArgs} args - Arguments to update or create a Context.
   * @example
   * // Update or create a Context
   * const context = await prisma.context.upsert({
   *   create: {
   *     // ... data to create a Context
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Context we want to update
   *   }
   * })
   */
  upsert<T extends ContextUpsertArgs>(args: Prisma.SelectSubset<T, ContextUpsertArgs<ExtArgs>>): Prisma.Prisma__ContextClient<runtime.Types.Result.GetResult<Prisma.$ContextPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Contexts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContextCountArgs} args - Arguments to filter Contexts to count.
   * @example
   * // Count the number of Contexts
   * const count = await prisma.context.count({
   *   where: {
   *     // ... the filter for the Contexts we want to count
   *   }
   * })
  **/
  count<T extends ContextCountArgs>(
    args?: Prisma.Subset<T, ContextCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ContextCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Context.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContextAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ContextAggregateArgs>(args: Prisma.Subset<T, ContextAggregateArgs>): Prisma.PrismaPromise<GetContextAggregateType<T>>

  /**
   * Group by Context.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContextGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ContextGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ContextGroupByArgs['orderBy'] }
      : { orderBy?: ContextGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ContextGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetContextGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Context model
 */
readonly fields: ContextFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Context.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ContextClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Context model
 */
export interface ContextFieldRefs {
  readonly id: Prisma.FieldRef<"Context", 'String'>
  readonly title: Prisma.FieldRef<"Context", 'String'>
  readonly content: Prisma.FieldRef<"Context", 'String'>
  readonly hook: Prisma.FieldRef<"Context", 'String'>
  readonly createdAt: Prisma.FieldRef<"Context", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Context findUnique
 */
export type ContextFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Context
   */
  select?: Prisma.ContextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Context
   */
  omit?: Prisma.ContextOmit<ExtArgs> | null
  /**
   * Filter, which Context to fetch.
   */
  where: Prisma.ContextWhereUniqueInput
}

/**
 * Context findUniqueOrThrow
 */
export type ContextFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Context
   */
  select?: Prisma.ContextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Context
   */
  omit?: Prisma.ContextOmit<ExtArgs> | null
  /**
   * Filter, which Context to fetch.
   */
  where: Prisma.ContextWhereUniqueInput
}

/**
 * Context findFirst
 */
export type ContextFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Context
   */
  select?: Prisma.ContextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Context
   */
  omit?: Prisma.ContextOmit<ExtArgs> | null
  /**
   * Filter, which Context to fetch.
   */
  where?: Prisma.ContextWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Contexts to fetch.
   */
  orderBy?: Prisma.ContextOrderByWithRelationInput | Prisma.ContextOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Contexts.
   */
  cursor?: Prisma.ContextWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Contexts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Contexts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Contexts.
   */
  distinct?: Prisma.ContextScalarFieldEnum | Prisma.ContextScalarFieldEnum[]
}

/**
 * Context findFirstOrThrow
 */
export type ContextFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Context
   */
  select?: Prisma.ContextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Context
   */
  omit?: Prisma.ContextOmit<ExtArgs> | null
  /**
   * Filter, which Context to fetch.
   */
  where?: Prisma.ContextWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Contexts to fetch.
   */
  orderBy?: Prisma.ContextOrderByWithRelationInput | Prisma.ContextOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Contexts.
   */
  cursor?: Prisma.ContextWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Contexts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Contexts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Contexts.
   */
  distinct?: Prisma.ContextScalarFieldEnum | Prisma.ContextScalarFieldEnum[]
}

/**
 * Context findMany
 */
export type ContextFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Context
   */
  select?: Prisma.ContextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Context
   */
  omit?: Prisma.ContextOmit<ExtArgs> | null
  /**
   * Filter, which Contexts to fetch.
   */
  where?: Prisma.ContextWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Contexts to fetch.
   */
  orderBy?: Prisma.ContextOrderByWithRelationInput | Prisma.ContextOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Contexts.
   */
  cursor?: Prisma.ContextWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Contexts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Contexts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Contexts.
   */
  distinct?: Prisma.ContextScalarFieldEnum | Prisma.ContextScalarFieldEnum[]
}

/**
 * Context create
 */
export type ContextCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Context
   */
  select?: Prisma.ContextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Context
   */
  omit?: Prisma.ContextOmit<ExtArgs> | null
  /**
   * The data needed to create a Context.
   */
  data: Prisma.XOR<Prisma.ContextCreateInput, Prisma.ContextUncheckedCreateInput>
}

/**
 * Context createMany
 */
export type ContextCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Contexts.
   */
  data: Prisma.ContextCreateManyInput | Prisma.ContextCreateManyInput[]
}

/**
 * Context createManyAndReturn
 */
export type ContextCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Context
   */
  select?: Prisma.ContextSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Context
   */
  omit?: Prisma.ContextOmit<ExtArgs> | null
  /**
   * The data used to create many Contexts.
   */
  data: Prisma.ContextCreateManyInput | Prisma.ContextCreateManyInput[]
}

/**
 * Context update
 */
export type ContextUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Context
   */
  select?: Prisma.ContextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Context
   */
  omit?: Prisma.ContextOmit<ExtArgs> | null
  /**
   * The data needed to update a Context.
   */
  data: Prisma.XOR<Prisma.ContextUpdateInput, Prisma.ContextUncheckedUpdateInput>
  /**
   * Choose, which Context to update.
   */
  where: Prisma.ContextWhereUniqueInput
}

/**
 * Context updateMany
 */
export type ContextUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Contexts.
   */
  data: Prisma.XOR<Prisma.ContextUpdateManyMutationInput, Prisma.ContextUncheckedUpdateManyInput>
  /**
   * Filter which Contexts to update
   */
  where?: Prisma.ContextWhereInput
  /**
   * Limit how many Contexts to update.
   */
  limit?: number
}

/**
 * Context updateManyAndReturn
 */
export type ContextUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Context
   */
  select?: Prisma.ContextSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Context
   */
  omit?: Prisma.ContextOmit<ExtArgs> | null
  /**
   * The data used to update Contexts.
   */
  data: Prisma.XOR<Prisma.ContextUpdateManyMutationInput, Prisma.ContextUncheckedUpdateManyInput>
  /**
   * Filter which Contexts to update
   */
  where?: Prisma.ContextWhereInput
  /**
   * Limit how many Contexts to update.
   */
  limit?: number
}

/**
 * Context upsert
 */
export type ContextUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Context
   */
  select?: Prisma.ContextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Context
   */
  omit?: Prisma.ContextOmit<ExtArgs> | null
  /**
   * The filter to search for the Context to update in case it exists.
   */
  where: Prisma.ContextWhereUniqueInput
  /**
   * In case the Context found by the `where` argument doesn't exist, create a new Context with this data.
   */
  create: Prisma.XOR<Prisma.ContextCreateInput, Prisma.ContextUncheckedCreateInput>
  /**
   * In case the Context was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ContextUpdateInput, Prisma.ContextUncheckedUpdateInput>
}

/**
 * Context delete
 */
export type ContextDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Context
   */
  select?: Prisma.ContextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Context
   */
  omit?: Prisma.ContextOmit<ExtArgs> | null
  /**
   * Filter which Context to delete.
   */
  where: Prisma.ContextWhereUniqueInput
}

/**
 * Context deleteMany
 */
export type ContextDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Contexts to delete
   */
  where?: Prisma.ContextWhereInput
  /**
   * Limit how many Contexts to delete.
   */
  limit?: number
}

/**
 * Context without action
 */
export type ContextDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Context
   */
  select?: Prisma.ContextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Context
   */
  omit?: Prisma.ContextOmit<ExtArgs> | null
}
